# Generated by Django 5.1.3 on 2024-11-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=12)),
                ('uf', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=20)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('instituicao', models.BooleanField(default=False)),
                ('aluno', models.BooleanField(default=False)),
                ('professor', models.BooleanField(default=False)),
            ],
        ),
    ]
