# Generated by Django 5.1.3 on 2024-11-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='liderComunitario',
            field=models.BooleanField(default=False),
        ),
    ]
