# Generated by Django 5.1.3 on 2024-11-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_usuario_lidercomunitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='liderComunitario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='professor',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(default='user', max_length=20),
            preserve_default=False,
        ),
    ]
